apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: identifier-producer
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: identifier-producer
  minReplicas: 2
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 80
